# Generated by Django 5.1.6 on 2025-03-05 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_category_rename_content_post_body_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='body',
            new_name='content',
        ),
    ]
